services:
  app:
    image: joaountura/cupom
    container_name: joaountura-cupom
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/demo
    volumes:
      - h2-data:/data
    restart: unless-stopped

volumes:
  h2-data: